# permissions for end users to edit testoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testoperator-editor-role
rules:
- apiGroups:
  - k8s.rahulp.tech
  resources:
  - testoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.rahulp.tech
  resources:
  - testoperators/status
  verbs:
  - get
